/** Downloads of files generated by the workers (QR sheet, order receipts). */

/** A file read from the api, ready to be saved. */
export interface DownloadedFile {
  blob: Blob;
  filename: string;
}

/**
 * Filename from a `Content-Disposition` header (`attachment; filename="comprobante-pedido-12.pdf"`).
 * Only plain names are accepted (no paths); anything else gives `fallback`.
 */
export function filenameFromDisposition(header: string | null, fallback: string): string {
  if (!header) return fallback;
  const encoded = /filename\*=UTF-8''([^;]+)/i.exec(header);
  let name: string | undefined;
  if (encoded?.[1]) {
    try {
      name = decodeURIComponent(encoded[1].trim());
    } catch {
      name = undefined;
    }
  }
  name ??= /filename="?([^";]+)"?/i.exec(header)?.[1]?.trim();
  return name && /^[\w .-]{1,120}$/.test(name) ? name : fallback;
}

/** How long a receipt download waits for the workers before giving up. */
export const RECEIPT_TIMEOUT_MS = 60_000;

/**
 * Wait before asking again for a receipt that is still being generated (202). The `order.receipt-ready`
 * event normally wakes the download much sooner; this is only the fallback when the event is missed.
 * @param attempt 0 for the first retry.
 */
export function receiptRetryDelay(attempt: number): number {
  const steps = [1_500, 3_000, 5_000, 8_000];
  return steps[Math.min(Math.max(0, attempt), steps.length - 1)]!;
}

/** Triggers a browser download of an in-memory file. */
export function saveBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.append(link);
  link.click();
  link.remove();
  // Revoking right away can cancel the download in some browsers.
  setTimeout(() => URL.revokeObjectURL(url), 30_000);
}
