import { ORDER_LIMITS, ORDER_STATUSES, type OrderStatus, PAYMENT_METHODS, type PaymentMethod } from "@app/types";
import { Transform, Type } from "class-transformer";
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsIn,
  IsInt,
  IsMongoId,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from "class-validator";

const trim = ({ value }: { value: unknown }) => (typeof value === "string" ? value.trim() : value);

export class TableDto {
  @Transform(trim)
  @IsString()
  @Length(1, 30, { message: "label debe tener entre 1 y 30 caracteres" })
  label!: string;
}

export class UpdateTableDto {
  @IsOptional()
  @Transform(trim)
  @IsString()
  @Length(1, 30, { message: "label debe tener entre 1 y 30 caracteres" })
  label?: string;

  @IsOptional()
  @IsBoolean()
  active?: boolean;
}

export class ModifierSelectionDto {
  @IsMongoId()
  groupId!: string;

  @IsArray()
  @ArrayMaxSize(30)
  @IsMongoId({ each: true })
  optionIds!: string[];
}

export class OrderItemDto {
  @IsMongoId()
  productId!: string;

  @IsInt()
  @Min(1)
  @Max(ORDER_LIMITS.quantityMax, { message: `quantity no puede superar ${ORDER_LIMITS.quantityMax}` })
  quantity!: number;

  @IsArray()
  @ArrayMaxSize(10)
  @ValidateNested({ each: true })
  @Type(() => ModifierSelectionDto)
  modifiers!: ModifierSelectionDto[];

  @IsOptional()
  @IsString()
  @MaxLength(ORDER_LIMITS.noteMax)
  note?: string;
}

export class CreateDineInOrderDto {
  /** Generated by the browser (crypto.randomUUID) once per submission. */
  @IsUUID("4", { message: "clientOrderId debe ser un UUID" })
  clientOrderId!: string;

  @IsArray()
  @ArrayMinSize(1, { message: "El pedido está vacío" })
  @ArrayMaxSize(ORDER_LIMITS.itemsMax)
  @ValidateNested({ each: true })
  @Type(() => OrderItemDto)
  items!: OrderItemDto[];

  @IsOptional()
  @IsString()
  @MaxLength(ORDER_LIMITS.customerNameMax)
  customerName?: string;

  @IsOptional()
  @IsString()
  @MaxLength(ORDER_LIMITS.noteMax)
  note?: string;
}

export class OrdersQueryDto {
  @IsOptional()
  @IsIn(["active", "today"])
  scope?: "active" | "today";
}

export class ChangeStatusDto {
  @IsIn(ORDER_STATUSES)
  status!: OrderStatus;

  @IsOptional()
  @IsString()
  @MaxLength(ORDER_LIMITS.rejectReasonMax)
  reason?: string;
}

export class PaymentDto {
  @IsIn(PAYMENT_METHODS, { message: `method debe ser uno de: ${PAYMENT_METHODS.join(", ")}` })
  method!: PaymentMethod;
}

/** The customer's tracking token travels in the body, never in the URL, so it stays out of access logs. */
export class AccessTokenDto {
  @IsString()
  @Length(20, 100)
  accessToken!: string;
}
