import {
  DELIVERY_ETA_MINUTES,
  GEO_LIMITS,
  DELIVERY_ZONE_LIMITS,
  ORDER_LIMITS,
  ORDER_STATUSES,
  type OrderStatus,
  PAYMENT_METHODS,
  type PaymentMethod,
  PICKUP_READY_MINUTES,
} from "@app/types";
import { applyDecorators } from "@nestjs/common";
import { Transform, Type } from "class-transformer";
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsEmail,
  IsIn,
  IsInt,
  IsMongoId,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Matches,
  ValidateIf,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from "class-validator";
import { cleanLine, cleanText } from "../../../common/validation/clean-text";
import { GeoPointDto } from "../../../common/validation/geo-point.dto";
import { PushSubscriptionDto } from "../../push/dto/push.dto";


export class TableDto {
  @Transform(cleanLine)
  @IsString()
  @Length(1, 30, { message: "label debe tener entre 1 y 30 caracteres" })
  label!: string;
}

export class UpdateTableDto {
  @IsOptional()
  @Transform(cleanLine)
  @IsString()
  @Length(1, 30, { message: "label debe tener entre 1 y 30 caracteres" })
  label?: string;

  @IsOptional()
  @IsBoolean()
  active?: boolean;
}

export class ModifierSelectionDto {
  @IsMongoId()
  groupId!: string;

  @IsArray()
  @ArrayMaxSize(30)
  @IsMongoId({ each: true })
  optionIds!: string[];
}

export class OrderItemDto {
  @IsMongoId()
  productId!: string;

  @IsInt()
  @Min(1)
  @Max(ORDER_LIMITS.quantityMax, { message: `quantity no puede superar ${ORDER_LIMITS.quantityMax}` })
  quantity!: number;

  @IsArray()
  @ArrayMaxSize(10)
  @ValidateNested({ each: true })
  @Type(() => ModifierSelectionDto)
  modifiers!: ModifierSelectionDto[];

  @IsOptional()
  @Transform(cleanText)
  @IsString()
  @MaxLength(ORDER_LIMITS.noteMax)
  note?: string;
}

export class CreateDineInOrderDto {
  /** Generated by the browser (crypto.randomUUID) once per submission. */
  @IsUUID("4", { message: "clientOrderId debe ser un UUID" })
  clientOrderId!: string;

  @IsArray()
  @ArrayMinSize(1, { message: "El pedido está vacío" })
  @ArrayMaxSize(ORDER_LIMITS.itemsMax)
  @ValidateNested({ each: true })
  @Type(() => OrderItemDto)
  items!: OrderItemDto[];

  @IsOptional()
  @Transform(cleanLine)
  @IsString()
  @MaxLength(ORDER_LIMITS.customerNameMax)
  customerName?: string;

  @IsOptional()
  @Transform(cleanText)
  @IsString()
  @MaxLength(ORDER_LIMITS.noteMax)
  note?: string;
}

export class CreatePickupOrderDto {
  /** Generated by the browser (crypto.randomUUID) once per submission. */
  @IsUUID("4", { message: "clientOrderId debe ser un UUID" })
  clientOrderId!: string;

  @IsArray()
  @ArrayMinSize(1, { message: "El pedido está vacío" })
  @ArrayMaxSize(ORDER_LIMITS.itemsMax)
  @ValidateNested({ each: true })
  @Type(() => OrderItemDto)
  items!: OrderItemDto[];

  @Transform(cleanLine)
  @IsString()
  @Length(2, ORDER_LIMITS.customerNameMax, { message: "Indica tu nombre (2 a 60 caracteres)" })
  customerName!: string;

  /** Format is checked and normalized by the service (normalizePhone, shared with the web). */
  @Transform(cleanLine)
  @IsString()
  @MaxLength(30)
  customerPhone!: string;

  @IsOptional()
  @Transform(({ value }: { value: unknown }) =>
    typeof value === "string" ? value.trim().toLowerCase() || undefined : value,
  )
  @IsEmail({}, { message: "customerEmail no es un correo válido" })
  @MaxLength(ORDER_LIMITS.customerEmailMax)
  customerEmail?: string;

  @IsOptional()
  @Transform(cleanText)
  @IsString()
  @MaxLength(ORDER_LIMITS.noteMax)
  note?: string;
}

export class DeliveryAddressDto {
  @IsMongoId({ message: "Elige la comuna o zona de entrega" })
  zoneId!: string;

  @Transform(cleanLine)
  @IsString()
  @Length(3, ORDER_LIMITS.addressMax, { message: "Indica la calle y el número" })
  address!: string;

  @IsOptional()
  @Transform(cleanLine)
  @IsString()
  @MaxLength(ORDER_LIMITS.addressUnitMax)
  unit?: string;

  @IsOptional()
  @Transform(cleanText)
  @IsString()
  @MaxLength(ORDER_LIMITS.addressReferenceMax)
  reference?: string;

  /** The customer's pin; required when the zone has an area drawn. */
  @IsOptional()
  @ValidateNested()
  @Type(() => GeoPointDto)
  location?: GeoPointDto;
}

export class ExpectedPaymentDto {
  @IsIn(PAYMENT_METHODS, { message: `method debe ser uno de: ${PAYMENT_METHODS.join(", ")}` })
  method!: PaymentMethod;

  /** Only meaningful with cash; the service checks it covers the total. */
  @ValidateIf((o: ExpectedPaymentDto) => o.cashAmount !== undefined && o.cashAmount !== null)
  @IsInt()
  @Min(1)
  @Max(100_000_000)
  cashAmount?: number;
}

export class CreateDeliveryOrderDto extends CreatePickupOrderDto {
  @ValidateNested()
  @Type(() => DeliveryAddressDto)
  delivery!: DeliveryAddressDto;

  @ValidateNested()
  @Type(() => ExpectedPaymentDto)
  payment!: ExpectedPaymentDto;
}

export class AssignRiderDto {
  /** null unassigns. */
  @ValidateIf((o: AssignRiderDto) => o.riderId !== null)
  @IsMongoId()
  riderId!: string | null;
}

/** Area of a zone: its vertices (3–200, validated by the service with geoAreaProblem). */
const AREA = [
  IsOptional(),
  ValidateIf((_: unknown, value: unknown) => value !== null),
  IsArray(),
  ArrayMaxSize(GEO_LIMITS.zoneVerticesMax),
  ValidateNested({ each: true }),
  Type(() => GeoPointDto),
];

export class DeliveryZoneDto {
  @Transform(cleanLine)
  @IsString()
  @Length(1, DELIVERY_ZONE_LIMITS.nameMax, { message: "name debe tener entre 1 y 60 caracteres" })
  name!: string;

  @IsInt()
  @Min(0)
  @Max(DELIVERY_ZONE_LIMITS.feeMax)
  fee!: number;

  @IsInt()
  @Min(0)
  @Max(100_000_000)
  minOrder!: number;

  @IsOptional()
  @IsBoolean()
  active?: boolean;

  @IsOptional()
  @IsBoolean()
  isHome?: boolean;

  @applyDecorators(...AREA)
  area?: GeoPointDto[] | null;
}

export class UpdateDeliveryZoneDto {
  @IsOptional()
  @Transform(cleanLine)
  @IsString()
  @Length(1, DELIVERY_ZONE_LIMITS.nameMax, { message: "name debe tener entre 1 y 60 caracteres" })
  name?: string;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(DELIVERY_ZONE_LIMITS.feeMax)
  fee?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100_000_000)
  minOrder?: number;

  @IsOptional()
  @IsBoolean()
  active?: boolean;

  @IsOptional()
  @IsBoolean()
  isHome?: boolean;

  /** null removes the area (the zone goes back to being chosen by name). */
  @applyDecorators(...AREA)
  area?: GeoPointDto[] | null;
}

export class CustomerOrdersQueryDto {
  /** The `nextBefore` of the previous page ("<ISO date>_<order id>"; the service parses it). */
  @IsOptional()
  @IsString()
  @MaxLength(60)
  before?: string;
}

export class DailySummaryQueryDto {
  @IsOptional()
  @Matches(/^\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/, { message: "date debe tener el formato AAAA-MM-DD" })
  date?: string;
}

export class OrdersQueryDto {
  @IsOptional()
  @IsIn(["active", "today"])
  scope?: "active" | "today";
}

export class ChangeStatusDto {
  @IsIn(ORDER_STATUSES)
  status!: OrderStatus;

  @IsOptional()
  @Transform(cleanText)
  @IsString()
  @MaxLength(ORDER_LIMITS.rejectReasonMax)
  reason?: string;

  /** Required when accepting pickup and delivery orders; the service checks the choices of each channel. */
  @IsOptional()
  @IsIn([...new Set([...PICKUP_READY_MINUTES, ...DELIVERY_ETA_MINUTES])], {
    message: "readyInMinutes no es una opción válida",
  })
  readyInMinutes?: number;
}

export class PaymentDto {
  @IsIn(PAYMENT_METHODS, { message: `method debe ser uno de: ${PAYMENT_METHODS.join(", ")}` })
  method!: PaymentMethod;
}

/** The customer's tracking token travels in the body, never in the URL, so it stays out of access logs. */
export class AccessTokenDto {
  @IsString()
  @Length(20, 100)
  accessToken!: string;
}

/** "Avísame" on the tracking page: the order's token plus the browser's push subscription. */
export class FollowOrderDto extends AccessTokenDto {
  @ValidateNested()
  @Type(() => PushSubscriptionDto)
  subscription!: PushSubscriptionDto;
}
