import type { OpenState } from "./restaurants";

/** Channels a customer can order through: dine_in (phase 3), pickup (phase 4), delivery (phase 5). */
export const ORDER_CHANNELS = ["dine_in", "pickup", "delivery"] as const;
export type OrderChannel = (typeof ORDER_CHANNELS)[number];

export const ORDER_STATUSES = [
  "pending",
  "accepted",
  "preparing",
  "ready",
  "served",
  "picked_up",
  "out_for_delivery",
  "delivered",
  "rejected",
  "cancelled",
] as const;
export type OrderStatus = (typeof ORDER_STATUSES)[number];

export const ORDER_STATUS_LABELS: Record<OrderStatus, string> = {
  pending: "Pendiente",
  accepted: "Aceptado",
  preparing: "En preparación",
  ready: "Listo",
  served: "Servido",
  picked_up: "Retirado",
  out_for_delivery: "En reparto",
  delivered: "Entregado",
  rejected: "Rechazado",
  cancelled: "Cancelado",
};

/** Statuses after which nothing else can happen to the order. */
export const FINAL_ORDER_STATUSES: readonly OrderStatus[] = ["served", "picked_up", "delivered", "rejected", "cancelled"];

export const PAYMENT_METHODS = ["cash", "card_pos", "transfer"] as const;
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

export const PAYMENT_METHOD_LABELS: Record<PaymentMethod, string> = {
  cash: "Efectivo",
  card_pos: "Tarjeta (POS)",
  transfer: "Transferencia",
};

export type PaymentStatus = "unpaid" | "paid";

export const ORDER_CHANNEL_LABELS: Record<OrderChannel, string> = {
  dine_in: "En la mesa",
  pickup: "Para retirar",
  delivery: "Delivery",
};

export const ORDER_LIMITS = {
  itemsMax: 50,
  quantityMax: 20,
  customerNameMax: 60,
  customerEmailMax: 254,
  noteMax: 200,
  rejectReasonMax: 200,
  /** Pickup/delivery orders still in progress allowed per phone and restaurant (stops floods of fake orders). */
  activePickupOrdersPerPhone: 3,
  addressMax: 120,
  addressUnitMax: 30,
  addressReferenceMax: 150,
} as const;

/** "Ready in" choices the staff picks when accepting a pickup order. */
export const PICKUP_READY_MINUTES = [10, 15, 20, 30, 45, 60] as const;
export type PickupReadyMinutes = (typeof PICKUP_READY_MINUTES)[number];

/** "Arrives in" choices the staff picks when accepting a delivery order. */
export const DELIVERY_ETA_MINUTES = [20, 30, 45, 60, 90] as const;
export type DeliveryEtaMinutes = (typeof DELIVERY_ETA_MINUTES)[number];

/** Time choices offered when accepting an order of a channel that needs one. */
export const READY_MINUTES_BY_CHANNEL: Partial<Record<OrderChannel, readonly number[]>> = {
  pickup: PICKUP_READY_MINUTES,
  delivery: DELIVERY_ETA_MINUTES,
};

// ── Requests ────────────────────────────────────────────────────────────────

/** A cart line as the customer sends it: ids and quantities only — the server prices everything. */
export interface OrderItemInput {
  productId: string;
  quantity: number;
  /** Chosen option ids per modifier group of the product. */
  modifiers: { groupId: string; optionIds: string[] }[];
  note?: string;
}

export interface CreateDineInOrderInput {
  /** Random id generated by the browser per submission, so retries never create duplicate orders. */
  clientOrderId: string;
  items: OrderItemInput[];
  customerName?: string;
  note?: string;
}

export interface CreatePickupOrderInput {
  /** Random id generated by the browser per submission, so retries never create duplicate orders. */
  clientOrderId: string;
  items: OrderItemInput[];
  customerName: string;
  /** Any common format; stored normalized (`+56912345678`). */
  customerPhone: string;
  /** Optional: when present, the confirmation with the PDF receipt is emailed. */
  customerEmail?: string;
  note?: string;
}

/** Where a delivery goes. The zone fixes the fee and the minimum order; the rest is free text. */
export interface DeliveryAddressInput {
  zoneId: string;
  /** Street and number. */
  address: string;
  /** Apartment, house, office. */
  unit?: string;
  /** How to find it ("portón verde", "frente a la plaza"). */
  reference?: string;
}

/** How the customer plans to pay on delivery; `cashAmount` lets the rider bring change. */
export interface ExpectedPaymentInput {
  method: PaymentMethod;
  /** Only with cash: the bill the customer will pay with (≥ total). */
  cashAmount?: number;
}

export interface CreateDeliveryOrderInput extends CreatePickupOrderInput {
  delivery: DeliveryAddressInput;
  payment: ExpectedPaymentInput;
}

/** Body of `POST /restaurants/:id/orders/:orderId/status`. */
export interface ChangeOrderStatusInput {
  status: OrderStatus;
  /** Mandatory when rejecting (shown to the customer). */
  reason?: string;
  /**
   * Mandatory when accepting a pickup (ready in, `PICKUP_READY_MINUTES`) or a delivery order (arrives in,
   * `DELIVERY_ETA_MINUTES`).
   */
  readyInMinutes?: number;
}

/** Body of `PUT /restaurants/:id/orders/:orderId/rider`: null unassigns. */
export interface AssignRiderInput {
  riderId: string | null;
}

// ── Views ───────────────────────────────────────────────────────────────────

/** Price snapshot of a chosen modifier option. */
export interface OrderItemModifier {
  groupName: string;
  optionName: string;
  priceDelta: number;
}

/** Price snapshot of a cart line: later menu changes never alter it. */
export interface OrderItemView {
  productId: string;
  name: string;
  unitPrice: number;
  quantity: number;
  modifiers: OrderItemModifier[];
  note: string;
  /** (unitPrice + Σ priceDelta) × quantity. */
  lineTotal: number;
}

/** Delivery details snapshot (zone name and fee as they were when ordering). */
export interface OrderDeliveryView {
  zoneId: string;
  zoneName: string;
  address: string;
  unit: string;
  reference: string;
}

export interface ExpectedPaymentView {
  method: PaymentMethod;
  cashAmount: number | null;
  /** cashAmount − total: change the rider must bring, or null. */
  change: number | null;
}

export interface OrderStatusChange {
  status: OrderStatus;
  at: string;
  /** Name of the staff member, or null when the customer or the system made the change. */
  byName: string | null;
  reason?: string;
}

/** An order as the restaurant staff sees it. */
export interface OrderView {
  id: string;
  /** Global per restaurant, never resets: receipts, support. */
  number: number;
  /** Resets every business day: what the kitchen calls out. */
  ticketNumber: number;
  businessDate: string;
  channel: OrderChannel;
  status: OrderStatus;
  statusHistory: OrderStatusChange[];
  paymentStatus: PaymentStatus;
  paymentMethod: PaymentMethod | null;
  items: OrderItemView[];
  subtotal: number;
  total: number;
  currency: string;
  customerName: string;
  /** Pickup and delivery; "" for dine-in. */
  customerPhone: string;
  customerEmail: string;
  note: string;
  tableLabel: string | null;
  /** Set on acceptance: pickup → when it will be ready; delivery → when it should arrive. */
  estimatedReadyAt: string | null;
  /** Whether the PDF receipt exists (pickup and delivery orders, once accepted). */
  receiptAvailable: boolean;
  /** Delivery only (null otherwise). */
  deliveryFee: number;
  delivery: OrderDeliveryView | null;
  expectedPayment: ExpectedPaymentView | null;
  rider: { id: string; name: string } | null;
  createdAt: string;
  /** Last write of any kind (status, payment, rider): tells which of two copies is newer. */
  updatedAt: string;
}

/** What the customer sees on the tracking page (no staff names, no internal ids). */
export interface PublicOrderView {
  ticketNumber: number;
  number: number;
  channel: OrderChannel;
  status: OrderStatus;
  /** Present when status is "rejected". */
  rejectReason: string | null;
  /** Present when status is "cancelled": the staff's reason, or "Cancelado por el cliente". */
  cancelReason: string | null;
  items: OrderItemView[];
  subtotal: number;
  deliveryFee: number;
  total: number;
  currency: string;
  tableLabel: string | null;
  /** Pickup: when it will be ready. Delivery: when it should arrive. */
  estimatedReadyAt: string | null;
  /** Delivery only: where it goes and how the customer said they would pay. */
  delivery: OrderDeliveryView | null;
  expectedPayment: ExpectedPaymentView | null;
  /** Delivery: first name of the assigned rider, if any. */
  riderName: string | null;
  /** Whether the PDF receipt can be downloaded (`POST /api/public/orders/receipt`). */
  receiptAvailable: boolean;
  restaurant: { name: string; slug: string; phone: string };
  createdAt: string;
  updatedAt: string;
  /** Whether the customer may still cancel (only while pending). */
  cancellable: boolean;
}

/** Response of a successful order: the access token is the customer's only key to the order. */
export interface CreatedOrder {
  accessToken: string;
  order: PublicOrderView;
}

// ── Tables ──────────────────────────────────────────────────────────────────

export interface TableView {
  id: string;
  label: string;
  /** Code printed in the QR: `<APP_URL>/m/<token>`. */
  token: string;
  active: boolean;
}

/** What the customer's phone gets after scanning a table QR. */
export interface TableContext {
  tableLabel: string;
  restaurant: { name: string; slug: string };
  acceptingOrders: boolean;
  openState: OpenState;
}

// ── Delivery zones ──────────────────────────────────────────────────────────

export const DELIVERY_ZONE_LIMITS = { nameMax: 60, zonesMax: 50, feeMax: 1_000_000 } as const;

/** A commune or sector the restaurant delivers to, with its fee and minimum order (minor units). */
export interface DeliveryZoneView {
  id: string;
  name: string;
  fee: number;
  minOrder: number;
  active: boolean;
  /** The restaurant's own commune: preselected at checkout. At most one zone has it. */
  isHome: boolean;
  position: number;
}

export interface DeliveryZoneInput {
  name: string;
  fee: number;
  minOrder: number;
  active?: boolean;
  isHome?: boolean;
}

/** `GET /api/public/restaurants/:slug/delivery-zones`: active zones, home first. */
export type PublicDeliveryZone = Pick<DeliveryZoneView, "id" | "name" | "fee" | "minOrder" | "isHome">;

/** A member with the rider role, for the assignment picker. */
export interface RiderView {
  id: string;
  name: string;
}

// ── Daily summary ───────────────────────────────────────────────────────────

/** Sales of one business day (orders rejected or cancelled count only in `orders`). Amounts in minor units. */
export interface DailySummary {
  /** Business date, YYYY-MM-DD in the restaurant's timezone. */
  date: string;
  currency: string;
  orders: { total: number; completed: number; inProgress: number; cancelled: number; rejected: number };
  sales: {
    /** Σ total of orders not rejected/cancelled (completed or in progress). */
    total: number;
    deliveryFees: number;
    paid: number;
    unpaid: number;
    /** total / orders counted, rounded; 0 without sales. */
    averageTicket: number;
  };
  byChannel: Record<OrderChannel, { orders: number; total: number }>;
  /** Paid amounts per method. */
  byPaymentMethod: Record<PaymentMethod, number>;
  /** Best sellers by units (top 5). */
  topProducts: { name: string; quantity: number; total: number }[];
}

// ── Real-time (Socket.IO) ───────────────────────────────────────────────────

/** Events the server emits. Rooms: `restaurant:<id>` (staff), `order:<id>` (the customer who placed it). */
export interface ServerToClientEvents {
  "order.created": (order: OrderView) => void;
  "order.updated": (order: OrderView) => void;
  "order.status": (order: PublicOrderView) => void;
  "restaurant.accepting": (payload: { restaurantId: string; acceptingOrders: boolean }) => void;
  "qr-sheet.ready": (payload: { restaurantId: string; jobId: string }) => void;
  /** The PDF receipt was generated (staff room and the customer's order room). */
  "order.receipt-ready": (payload: { orderId: string }) => void;
}

/** Events the client emits. Acks return `{ ok: true }` or `{ ok: false, code }`. */
export interface ClientToServerEvents {
  "restaurant.subscribe": (restaurantId: string, ack: (result: SubscribeResult) => void) => void;
  "order.subscribe": (accessToken: string, ack: (result: SubscribeResult) => void) => void;
}

export type SubscribeResult = { ok: true } | { ok: false; code: string };
